import { Exo_2 } from 'next/font/google'
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Mubin Resume",
  description: "Generated by create next app",
};
 
const exoTwo = Exo_2({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={exoTwo.className}>
        
        {children}
       
      </body>
    </html>
  );
}
